In [1]:
from numpy import matrix
from numpy import linalg
A = matrix( [[1,2,3],[11,12,13],[21,22,23]]) # Creates a matrix.
x = matrix( [[1],[2],[3]] )                  # Creates a matrix (like a column vector).
y = matrix( [[1,2,3]] )                      # Creates a matrix (like a row vector).
print (A.T)                                    # Transpose of A.
print (A*x )                                   # Matrix multiplication of A and x.
print( A.I  )                                  # Inverse of A.
print (linalg.solve(A, x)  )   # Solve the linear equation system.

[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]]
[[ 14]
 [ 74]
 [134]]
[[  3.00239975e+14  -6.00479950e+14   3.00239975e+14]
 [ -6.00479950e+14   1.20095990e+15  -6.00479950e+14]
 [  3.00239975e+14  -6.00479950e+14   3.00239975e+14]]
[[ 0.03333333]
 [-0.76666667]
 [ 0.83333333]]
